development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: example_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: example_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: example_prod
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
